### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Cyber-MC** [ajan-12/SlimefunFix#1]
Hey there,

I saw that you recently became a developer for SF itself, and I am here now to create a suggestion for this add-on. 

_Update to 1.14.4_
The reason for this is because it would follow the flow of newer updates for SF as they begin to come out.
_Add Machines to the list of items that get fixed via the GUI_
The reason for this is because machines actually become corrupted too, unfortunately.

This concludes my suggestion. :)

**Comment by QalleVcs** [comment]
Machines that are not identifiable by a custom name or other block data, such as the electric gold pan and washer, cannot be detected and thus cannot be fixed. Please provide the Base64 textures of the skull items that you have found do not get fixed.

**Comment by Cyber-MC** [comment]
> Machines that are not identifiable by a custom name or other block data, such as the electric gold pan and washer, cannot be detected and thus cannot be fixed. Please provide the Base64 textures of the skull items that you have found do not get fixed.

I don't believe I ever said anything about any skull items that aren't getting fixed. This issue was just a suggestion & I also believe that if he was able to fix Auto-Enchanters and Disenchanters, then the other machines are possible to be fixed as well.

**Comment by LinoxGH** [comment]
Auto-Enchanters and Disenchanters are enchanting tables meaningthey keep their names after being placed but this isn't the case for most other SF machine.

I mean I probably can add support for Electric Ore Grinder and new Auto Drier but those machines without a tile-entity cannot be fixed by this plugin.(f.e Electric Dust Washer...)

Note: I'm the person continuing ajan's plugin(s).

**Comment by ajan-12** [comment]
That's correct LinoxGH is my new account and for some time that account will have my new plugins, including https://github.com/LinoxGH/TheNewAdminshop.

**Comment by LinoxGH** [comment]
1.14 support is now a thing.
